id: RemoteAccessTest
version: -1
name: RemoteAccessTest
description: Test playbook for remote access
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 13810fbc-783e-4a92-884c-0b6454988cc3
    type: start
    task:
      id: 13810fbc-783e-4a92-884c-0b6454988cc3
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 65
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "1":
    id: "1"
    taskid: 30f641af-a0da-4d20-8aec-a7d9487a30f9
    type: regular
    task:
      id: 30f641af-a0da-4d20-8aec-a7d9487a30f9
      version: -1
      name: Create File In Cortex XSOAR
      description: |
        Will create a file (using the given data input or entry ID) and upload it to current investigation war room.
      scriptName: FileCreateAndUpload
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "2"
    scriptarguments:
      data:
        simple: test
      filename:
        simple: test.txt
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 225
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "2":
    id: "2"
    taskid: d9d20c2e-eb0a-44fc-88de-afd728ea5905
    type: regular
    task:
      id: d9d20c2e-eb0a-44fc-88de-afd728ea5905
      version: -1
      name: Copy File To Remote
      description: Copies the given file from Cortex XSOAR to the remote machine.
      script: RemoteAccess v2|||copy-to
      type: regular
      iscommand: true
      brand: RemoteAccess v2
    nexttasks:
      '#none#':
      - "4"
    scriptarguments:
      destination_path:
        simple: test-TPB/test.txt
      entry_id:
        complex:
          root: File
          accessor: EntryID
          transformers:
          - operator: LastArrayElement
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 400
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "4":
    id: "4"
    taskid: 5085cada-259b-4e49-88ce-eed759f6c4f6
    type: regular
    task:
      id: 5085cada-259b-4e49-88ce-eed759f6c4f6
      version: -1
      name: Run ls Command Remote
      description: Run command on remote system with ssh
      script: '|||ssh'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "5"
    scriptarguments:
      cmd:
        simple: ls test-TPB
      command:
        simple: ls test
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 575
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "5":
    id: "5"
    taskid: 906f4e99-0181-4fd8-841f-b005631a54da
    type: condition
    task:
      id: 906f4e99-0181-4fd8-841f-b005631a54da
      version: -1
      name: Validate File Is Found In ls
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "6"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: containsGeneral
          left:
            value:
              complex:
                root: RemoteAccess.Command
                accessor: output
            iscontext: true
          right:
            value:
              simple: test.txt
    view: |-
      {
        "position": {
          "x": 50,
          "y": 750
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "6":
    id: "6"
    taskid: dc689ec6-0b7d-4eb4-841a-8132e4a4e144
    type: regular
    task:
      id: dc689ec6-0b7d-4eb4-841a-8132e4a4e144
      version: -1
      name: Copy File To Local
      description: Copies the given file from the remote machine to Cortex XSOAR.
      script: RemoteAccess v2|||copy-from
      type: regular
      iscommand: true
      brand: RemoteAccess v2
    nexttasks:
      '#none#':
      - "7"
    scriptarguments:
      file_name:
        simple: test-file-from-remote.txt
      file_path:
        simple: test-TPB/test.txt
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 925
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "7":
    id: "7"
    taskid: 9c14de43-e150-497f-859e-cecb12dfa13a
    type: condition
    task:
      id: 9c14de43-e150-497f-859e-cecb12dfa13a
      version: -1
      name: See File Was Copied
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "9"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: containsGeneral
          left:
            value:
              simple: File.Name
            iscontext: true
          right:
            value:
              simple: test-file-from-remote.txt
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1100
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "8":
    id: "8"
    taskid: c5893e33-4f82-4ff4-8e8a-db9bc7ddc187
    type: title
    task:
      id: c5893e33-4f82-4ff4-8e8a-db9bc7ddc187
      version: -1
      name: Playbook Done
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1450
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "9":
    id: "9"
    taskid: 3275417f-22ac-4538-863a-232660d75d99
    type: regular
    task:
      id: 3275417f-22ac-4538-863a-232660d75d99
      version: -1
      name: Remove Folder From Remote
      description: Run the specified command on the remote system with SSH.
      script: RemoteAccess v2|||ssh
      type: regular
      iscommand: true
      brand: RemoteAccess v2
    nexttasks:
      '#none#':
      - "8"
    scriptarguments:
      cmd:
        simple: rm -rf test-TPB
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1275
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1450,
        "width": 380,
        "x": 50,
        "y": 65
      }
    }
  }
inputs: []
outputs: []
fromversion: 6.0.0